name: watch_connectivity
description: Wrapper for WatchConnectivity on iOS and Wearable APIs on Android
version: 0.1.5
homepage: https://github.com/Rexios80/watch_connectivity/tree/master/watch_connectivity

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  watch_connectivity_platform_interface: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  rexios_lints: ^5.0.0

# dependency_overrides:
#   watch_connectivity_platform_interface:
#     path: ../watch_connectivity_platform_interface

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: WatchConnectivityPlugin
